# api key

In [1]:
# 파일을 읽기 모드로 열기
with open("C:\\Users\\lee\\Desktop\\bybit\\api.txt", "r") as file:
    f = []
    # 파일의 각 줄에 대해 반복
    for line in file:
        # 각 줄 출력
        f.append(line.strip())  # strip()은 줄 바꿈 문자(\n) 등을 제거하여 출력합니다.

In [1]:
from pybit.unified_trading import HTTP
from datetime import datetime
import math

now = datetime.now()
now_timestamp = math.floor(now.timestamp()*1000)


session = HTTP(testnet=True)
price = session.get_mark_price_kline(
    category="linear",
    symbol="BTCUSDT",
    interval=1,
    start=now_timestamp-60000000,
    end=now_timestamp,
    limit=1000,
)

now_time = price['time']


In [2]:
a_hundred_prices = price['result']['list']
highPrice = []
lowPrice = []
closePrice = []
for i in range(len(a_hundred_prices)):
    highPrice.append(float(a_hundred_prices[i][2]))
    lowPrice.append(float(a_hundred_prices[i][3]))
    closePrice.append(float(a_hundred_prices[i][4]))

# 가장 최신 가격을 앞에서 뒤로 변경하기 위한 코드
highPrice_reverse = highPrice[::-1]
lowPrice_reverse = lowPrice[::-1]
closePrice_reverse = closePrice[::-1]

# EMA

In [3]:
import talib
import numpy as np

price_data = np.array(closePrice_reverse)

ema_period = 50
ema_values = talib.EMA(price_data, timeperiod=ema_period)

ema_values


array([           nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan, 37418.18      , 37418.32196078, 37418.37325644,
       37419.16646207, 37419.79797336, 37420.41962146, 37421.50159709,
      

# RSI

In [4]:
import talib
import numpy as np

price_data = np.array(closePrice_reverse)

rsi_period = 14
rsi_values = talib.RSI(price_data, timeperiod=rsi_period)

rsi_values


array([        nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan, 15.79547924,
       14.23754483, 14.03819733, 13.54791736, 16.53539519, 15.67034789,
       15.35975997, 14.86907929, 13.59528408, 12.07253991, 11.85999864,
       27.81044856, 30.27261639, 31.96144145, 45.08769182, 48.7078242 ,
       47.8981526 , 47.3129639 , 48.94630686, 56.59354093, 56.64230987,
       47.63417524, 44.87463731, 47.30085762, 37.30462147, 39.84991048,
       43.33189295, 48.94196232, 51.12246394, 48.55455187, 53.68722307,
       52.64485008, 53.51466113, 52.13052684, 48.95984184, 52.00230685,
       53.71888246, 52.86914275, 58.97809889, 57.56750924, 57.6918627 ,
       61.63065675, 61.75784057, 55.27527639, 52.56244688, 60.44838481,
       60.4788818 , 60.60971758, 62.89184784, 67.96169139, 69.2789705 ,
       70.8000639 , 71.97080803, 73.29792495, 73.74093976, 78.46

# ADX

In [5]:
import talib
import numpy as np

high_data = np.array(highPrice_reverse)
low_data = np.array(lowPrice_reverse)
close_data = np.array(closePrice_reverse)

adx_period = 14
adx_values = talib.ADX(high_data, low_data, close_data, timeperiod=adx_period)

adx_values

array([        nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan, 67.52952232, 63.31254181, 58.82183185,
       54.79871126, 50.96372422, 47.50934422, 45.31615568, 43.43664905,
       40.34959873, 37.90621391, 36.31761964, 35.40346551, 34.5649256 ,
       33.44100689, 31.41945955, 29.18648357, 27.59674086, 25.70487026,
       23.94813328, 22.31687751, 20.94738372, 19.73836549, 18.61570569,
       17.47705459, 16.41973571, 16.30986611, 16.20784433, 16.1008647 ,
       16.72001214, 17.47873768, 17.06003826, 16.13896826, 16.27180881,
       16.40057552, 16.60058602, 17.12522754, 18.48322088, 19.96950583,
       21.57133232, 23.46317232, 25.21988088, 26.92022289, 29.21

# 실시간 호가

In [13]:
from pybit.unified_trading import WebSocket
from time import sleep
from datetime import datetime


ws = WebSocket(
    testnet=True,
    channel_type="linear",
)
def handle_message(message):
    close_price = message['data'][0]['close']
    time = datetime.utcfromtimestamp(message['ts']/1000)
    print(close_price, time)
    # print(message)
ws.kline_stream(
    interval=1,
    symbol="BTCUSDT",
    callback=handle_message
)
while True:
    sleep(1)

37281.8 2023-11-21 17:05:36.578000
37280.2 2023-11-21 17:05:37.578000
37280.1 2023-11-21 17:05:38.580000
37281.3 2023-11-21 17:05:39.579000
37279.6 2023-11-21 17:05:40.578000
37283 2023-11-21 17:05:41.579000
37284.2 2023-11-21 17:05:42.578000
37282.9 2023-11-21 17:05:43.577000
37286.2 2023-11-21 17:05:44.577000
37286.2 2023-11-21 17:05:45.580000
37290.4 2023-11-21 17:05:46.578000
37290 2023-11-21 17:05:47.577000
37290.4 2023-11-21 17:05:48.578000
37292.5 2023-11-21 17:05:50.579000
37292.5 2023-11-21 17:05:51.578000
37292.5 2023-11-21 17:05:52.579000
37292.5 2023-11-21 17:05:53.579000
37292.5 2023-11-21 17:05:54.579000
37292.5 2023-11-21 17:05:55.577000
37292.4 2023-11-21 17:05:56.578000
37290.4 2023-11-21 17:05:58.579000
37283.5 2023-11-21 17:05:59.577000
37283.5 2023-11-21 17:06:00.577000
37283.5 2023-11-21 17:06:01.577000
37278.2 2023-11-21 17:06:02.577000
37276.6 2023-11-21 17:06:03.578000
37278 2023-11-21 17:06:04.578000
37278 2023-11-21 17:06:05.578000
37277.5 2023-11-21 17:06:06.

In [12]:
closePrice

[37247.78,
 37214.4,
 37180.19,
 37175.15,
 37182.5,
 37197.7,
 37154.38,
 37144.8,
 37095.61,
 37141.89,
 37126.0,
 37204.93,
 37253.14,
 37184.69,
 37097.65,
 37111.82,
 37027.48,
 37020.69,
 36966.99,
 36978.0,
 36949.6,
 36961.78,
 36944.1,
 36912.67,
 36921.2,
 36952.65,
 36964.22,
 36977.83,
 36975.4,
 36896.9,
 36880.53,
 36868.09,
 36891.1,
 36900.0,
 36972.77,
 36967.64,
 36942.9,
 36940.64,
 36922.6,
 36973.67,
 36957.58,
 36930.0,
 36907.5,
 36927.01,
 36891.4,
 36901.02,
 36936.3,
 36970.4,
 36954.41,
 36966.91,
 36988.68,
 37042.09,
 37041.91,
 36996.6,
 36944.44,
 36929.5,
 36885.23,
 36878.7,
 36862.3,
 36849.03,
 36815.4,
 36876.33,
 36913.75,
 36891.05,
 36972.33,
 36986.9,
 36971.71,
 36971.57,
 36949.98,
 36980.68,
 37040.96,
 37082.21,
 37188.0,
 37084.83,
 37043.9,
 36913.51,
 36930.06,
 36935.71,
 36792.99,
 36544.1,
 36562.5,
 36548.8,
 36536.74,
 36506.4,
 36519.25,
 36520.6,
 36532.96,
 36513.9,
 36429.9,
 36405.08,
 36409.6,
 36447.62,
 36413.8,
 36417.0,
 364