# api key

In [1]:
# 파일을 읽기 모드로 열기
with open("C:\\Users\\lee\\Desktop\\bybit\\api.txt", "r") as file:
    f = []
    # 파일의 각 줄에 대해 반복
    for line in file:
        # 각 줄 출력
        f.append(line.strip())  # strip()은 줄 바꿈 문자(\n) 등을 제거하여 출력합니다.

# 캔들 마크 가격

In [1]:
from pybit.unified_trading import HTTP
from datetime import datetime
import math

now = datetime.now()
now_timestamp = math.floor(now.timestamp()*1000)

# get_kline / get_mark_price_kline
session = HTTP(testnet=True)
price = session.get_mark_price_kline(
    category="linear",
    symbol="BTCUSDT",
    interval=1,
    start=now_timestamp-60000000,
    end=now_timestamp,
    limit=1000,
)

now_time = price['time']


In [2]:
a_hundred_prices = price['result']['list']
highPrice = []
lowPrice = []
closePrice = []
for i in range(len(a_hundred_prices)):
    # a = float(a_hundred_prices[i][2])
    # b = float(a_hundred_prices[i][3])
    # c = float(a_hundred_prices[i][4])
    # highPrice.append(a)
    # lowPrice.append(b)
    # closePrice.append(c)

    highPrice.append(float(a_hundred_prices[i][2]))
    lowPrice.append(float(a_hundred_prices[i][3]))
    closePrice.append(float(a_hundred_prices[i][4]))

# 가장 최신 가격을 앞에서 뒤로 변경하기 위한 코드
highPrice_reverse = highPrice[::-1]
lowPrice_reverse = lowPrice[::-1]
closePrice_reverse = closePrice[::-1]

# EMA

In [3]:
import talib
import numpy as np

price_data = np.array(closePrice_reverse)

ema_period = 50
ema_values = talib.EMA(price_data, timeperiod=ema_period)

ema_values


array([           nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan, 37469.5374    , 37472.48377647, 37475.425197  ,
       37479.259503  , 37483.66501269, 37488.56050239, 37493.36205131,
      

# RSI

In [4]:
import talib
import numpy as np

price_data = np.array(closePrice_reverse)

rsi_period = 14
rsi_values = talib.RSI(price_data, timeperiod=rsi_period)

rsi_values


array([        nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan, 41.49494949,
       44.59455482, 46.36272973, 45.70719096, 52.08528052, 50.95369962,
       51.08429954, 55.25756355, 55.39351244, 50.01653658, 47.73810215,
       55.89949106, 55.93143618, 56.06851849, 58.46847922, 63.86085123,
       65.27583242, 66.91696565, 68.18540495, 69.6288799 , 70.11207121,
       75.31102251, 75.18298668, 77.30806442, 77.52484522, 78.45696061,
       80.74629998, 75.42860407, 75.47574033, 78.39874926, 81.4831065 ,
       82.28278873, 84.99933322, 85.21048586, 65.65935377, 62.70155598,
       56.39199578, 57.29028385, 64.47515887, 68.55251696, 71.75867776,
       72.2100401 , 77.15625442, 67.76822219, 68.24419825, 59.74741971,
       56.87107255, 64.28415734, 57.62749837, 61.71032013, 54.85041271,
       53.40710916, 51.88521911, 51.59004688, 51.38969294, 55.18

# ADX

In [5]:
import talib
import numpy as np

high_data = np.array(highPrice_reverse)
low_data = np.array(lowPrice_reverse)
close_data = np.array(closePrice_reverse)

adx_period = 14
adx_values = talib.ADX(high_data, low_data, close_data, timeperiod=adx_period)

adx_values

array([        nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan, 12.68020359, 12.6186011 , 13.57731642,
       14.72999034, 16.05843497, 17.76242205, 19.34469577, 20.89429013,
       23.16946986, 25.53130002, 27.77892384, 30.34635609, 31.26005304,
       32.33941796, 33.48687344, 34.08451828, 35.13343658, 36.65024436,
       38.09891902, 40.0670094 , 41.89452189, 42.32780653, 42.05803213,
       40.91132939, 39.61611392, 39.36498614, 39.66590958, 40.51261081,
       41.43139228, 42.7321805 , 43.94005527, 45.43217239, 45.55690789,
       45.13306316, 45.62216253, 46.07632622, 46.49804965, 46.30507673,
       45.98218491, 45.40489276, 44.56110446, 43.74355436, 43.41

# 실시간 호가

In [29]:
from pybit.unified_trading import WebSocket
from time import sleep
from datetime import datetime


ws = WebSocket(
    testnet=True,
    channel_type="linear",
)
def handle_message(message):
    close_price = message['data'][0]['close']
    time = datetime.utcfromtimestamp(message['ts']/1000)
    print(close_price, time)
    # print(message)
ws.kline_stream(
    interval=1,
    symbol="BTCUSDT",
    callback=handle_message
)
while True:
    sleep(1)

37125 2023-11-21 17:37:07.579000
